linux-tegra: fix devicetree dependency race
When building with kernel-modules, there's a race condition
which causes build errors during the link step for the modules
scripts.  These take various forms but look something like

```
|   CC      scripts/mod/empty.o
|   MKELF   scripts/mod/elfconfig.h
|   HOSTCC  scripts/mod/modpost.o
|   CC      scripts/mod/devicetable-offsets.s
|   CHK     scripts/mod/devicetable-offsets.h
|   HOSTLD  scripts/mod/modpost
| /build/tmp/hosttools/ld: scripts/mod/modpost.o: in function `read_symbols':
| modpost.c:(.text+0x1f7a): undefined reference to `handle_moddevtable'
| /build/tmp/hosttools/ld: modpost.c:(.text+0x26ed): undefined reference to `maybe_frob_rcs_version'
| /build/tmp/hosttools/ld: modpost.c:(.text+0x2705): undefined reference to `get_src_version'
| /build/tmp/hosttools/ld: scripts/mod/modpost.o: in function `main':
| modpost.c:(.text.startup+0x73f): undefined reference to `add_moddevtable'
```
and occurs in either the do_compile_kernelmodules or
do_compile_devicetree_overlays step, where the common thing with each failure
happening during the HOSTLD scripts/mod/modpost step.

To resolve, run do_compile_devicetree_overlays after do_compile_kernelmodules
instead of after do_compile.  This ensures that the do_compile_devicetree_overlays
step doesn't run concurrent with the scripts build of the do_compile_kernelmodules
step and stomp on each other with kernel build output.

1: https://github.com/yoctoproject/poky/blob/63d05fc061006bf1a88630d6d91cdc76ea33fbf2/meta/classes/module-base.bbclass#L5