tegra-flashvars: Fix xavier-nx-devkit for JP 5.0.1
Back out the change from [1] for R32.7.1 on flashvars setting for
Xavier NX which references the `tegra194-mb1-bct-misc-sd-l4t.cfg`
file, which doesn't exist in the tegraflash package for xavier-nx-devkit
on the 5.0.1 Jetpack release.

Instead, use the same file used in the p3668.conf.common file from the
nvidia_sdk/JetPack_5.0.1_DP_Linux_JETSON_XAVIER_NX_TARGETS/Linux_for_Tegra
directory on NVIDIA's deployment, tegra194-mb1-bct-misc-l4t.cfg (without
the `-sd-` in the filename).

This resolves the error below found when attempting to doflash.sh Jetpack 5
on Xavier NX Devkit SDCard version
```
Traceback (most recent call last):
  File "tegraflash.py", line 1360, in <module>
    tegraflash_run_commands()
  File "tegraflash.py", line 1208, in tegraflash_run_commands
    interpreter.onecmd(command)
  File "/usr/lib/python3.8/cmd.py", line 217, in onecmd
    return func(arg)
  File "tegraflash.py", line 261, in do_flash
    self.chip_inst.tegraflash_flash(exports)
  File "/home/yocto/tegraflash/wip-jp-5-dp/deploy/tegraflash_internal.py", line 360, in tegraflash_flash
    tegraflash_generate_bct()
  File "/home/yocto/tegraflash/wip-jp-5-dp/deploy/tegraflash_internal.py", line 4081, in tegraflash_generate_bct
    tegraflash_generate_mb1_bct(True) # generates coldboot mb1-bct
  File "/home/yocto/tegraflash/wip-jp-5-dp/deploy/tegraflash_internal.py", line 3979, in tegraflash_generate_mb1_bct
    concatenate_misc_cfg()
  File "/home/yocto/tegraflash/wip-jp-5-dp/deploy/tegraflash_internal.py", line 3363, in concatenate_misc_cfg
    concat_file(final_cold_boot_cfg, misc_cold_boot_cfg)
  File "/home/yocto/tegraflash/wip-jp-5-dp/deploy/tegraflash_internal.py", line 3336, in concat_file
    with open(infilename, 'rb') as infile:
FileNotFoundError: [Errno 2] No such file or directory: 'tegra194-mb1-bct-misc-sd-l4t.cfg
```

1: https://github.com/OE4T/meta-tegra/commit/c50e61928cc6cda27ce1ed51a9dbe031705b5ffb#diff-22c2c44733b697eea7b187b53aa82458a4617d64019d64dcbf9ddc0fec414474R5

Signed-off-by: Dan Walkes <danwalkes@trellis-logic.com>